Bot:
  Token: ''
  LogChannelID: ''
  WhitelistChannelID: ''
  WhitelistRoleIDs:
    - ''
  Prefix: '!'
  AutoResponseCooldown: 10000
  Activity: 'on survivalLABS'
  VerificationRoleID: ''
Commands:
  MapURL: ''
# MySQL or SQLite
StorageMode: 'SQLite'
SQLite:
  Path: 'plugins/survivalBOT/'
MySQL:
  Host: 'localhost'
  Database: 'survivalBOT'
  Username: ''
  Password: ''
  Port: '3306'
